### ISSUE TITLE
Sign up with the referral link should generate new referral link

### ISSUE THREAD

**Issue by dandv** [keryi/test-meteor-referral#2]
1. `meteor run`
2. Register
3. Get referral link
4. Navigate in incognito browser to referral link
5. Register.

Nothing happens when clicking Sign Up. No console error. Clicking sign up again shows an error that the email address already exists.

![meteor referral can t sign up](https://cloud.githubusercontent.com/assets/33569/8051734/11289bb0-0e35-11e5-8b25-6db9b3776abb.gif)

I can login at localhost:3000 with that email/pass, but I get the same referral link as for the first user.

**Comment by keryi** [comment]
Will look into this.

**Comment by keryi** [comment]
Hi, just fixed the 2 issues mentioned.
1. Get the incorrect referralUrl is autopublish. Remove autopublish has solved this issue.
2. Nothing happens when sign up is solved by adding a redirect route in AccountsTemplates configuration.
